name: deepseek
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=51_gnu
  - bzip2=1.0.8=h998d150_6
  - ca-certificates=2024.12.31=hd43f75c_0
  - ld_impl_linux-aarch64=2.40=h48e3ba3_0
  - libffi=3.4.4=h419075a_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h998d150_0
  - ncurses=6.4=h419075a_0
  - openssl=3.0.15=h998d150_0
  - pip=24.2=py310hd43f75c_0
  - python=3.10.16=h4bb2201_1
  - readline=8.2=h998d150_0
  - sqlite=3.45.3=h998d150_0
  - tk=8.6.14=h987d8db_0
  - wheel=0.44.0=py310hd43f75c_0
  - xz=5.4.6=h998d150_1
  - zlib=1.2.13=h998d150_1
  - pip:
      - absl-py==2.1.0
      - accelerate==1.0.1
      - aiofiles==23.2.1
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.11.11
      - aiosignal==1.3.2
      - annotated-types==0.7.0
      - anyio==4.8.0
      - asttokens==3.0.0
      - astunparse==1.6.3
      - async-timeout==5.0.1
      - attrs==24.3.0
      - audioread==3.0.1
      - av==14.0.1
      - beautifulsoup4==4.13.3
      - cbor==1.0.0
      - certifi==2024.12.14
      - cffi==1.17.1
      - charset-normalizer==3.4.1
      - click==8.1.8
      - cloudpickle==3.1.1
      - cmake==3.31.4
      - contourpy==1.3.1
      - cycler==0.12.1
      - datasets==2.21.0
      - decorator==5.1.1
      - deepspeed==0.13.2
      - dill==0.3.8
      - diskcache==5.6.3
      - distro==1.9.0
      - docker==7.1.0
      - docstring-parser==0.16
      - einops==0.8.0
      - et-xmlfile==2.0.0
      - exceptiongroup==1.2.2
      - fastapi==0.115.6
      - ffmpy==0.5.0
      - filelock==3.16.1
      - fire==0.7.0
      - flagembedding==1.3.4
      - fonttools==4.55.3
      - frozenlist==1.5.0
      - fsspec==2024.6.1
      - gradio==4.44.1
      - gradio-client==1.3.0
      - h11==0.14.0
      - hjson==3.1.0
      - httpcore==1.0.7
      - httptools==0.6.4
      - httpx==0.28.1
      - huggingface-hub==0.27.1
      - idna==3.10
      - ijson==3.3.0
      - importlib-resources==6.5.2
      - inscriptis==2.5.3
      - interegular==0.3.3
      - ir-datasets==0.5.10
      - jieba==0.42.1
      - jinja2==3.1.5
      - jiter==0.8.2
      - jmespath==1.0.1
      - joblib==1.4.2
      - json-repair==0.47.4
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - kiwisolver==1.4.8
      - lark==1.2.2
      - lazy-loader==0.4
      - librosa==0.10.2.post1
      - llamafactory==0.9.2.dev0
      - llvmlite==0.44.0
      - lm-format-enforcer==0.10.1
      - lxml==5.3.1
      - lz4==4.4.3
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.10.0
      - mdurl==0.1.2
      - mindspore==2.5.0
      - ml-dtypes==0.5.1
      - modelscope==1.22.3
      - mpmath==1.3.0
      - msgpack==1.1.0
      - multidict==6.1.0
      - multiprocess==0.70.16
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - ninja==1.11.1.3
      - nltk==3.9.1
      - numba==0.61.0
      - numpy==1.26.4
      - nvidia-ml-py==12.560.30
      - nvitop==1.4.2
      - openai==1.61.0
      - openmind==1.0.0
      - openmind-hub==0.9.1
      - openpyxl==3.1.5
      - orjson==3.10.14
      - outlines==0.0.34
      - packaging==24.2
      - pandas==2.2.3
      - peft==0.12.0
      - pillow==10.4.0
      - platformdirs==4.3.6
      - pooch==1.8.2
      - prometheus-client==0.21.1
      - prometheus-fastapi-instrumentator==7.0.2
      - propcache==0.2.1
      - protobuf==5.29.3
      - psutil==6.1.1
      - py-cpuinfo==9.0.0
      - pyarrow==18.1.0
      - pycparser==2.22
      - pydantic==2.10.5
      - pydantic-core==2.27.2
      - pydub==0.25.1
      - pygments==2.19.1
      - pynvml==11.5.0
      - pyparsing==3.2.1
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - python-multipart==0.0.20
      - pytz==2024.2
      - pyyaml==6.0.2
      - ray==2.42.0
      - referencing==0.36.2
      - regex==2024.11.6
      - requests==2.32.2
      - rich==13.9.4
      - rouge-chinese==1.0.3
      - rouge-score==0.1.2
      - rpds-py==0.22.3
      - ruff==0.9.1
      - safetensors==0.5.2
      - scikit-learn==1.6.1
      - scipy==1.15.1
      - semantic-version==2.10.0
      - sentence-transformers==3.4.1
      - sentencepiece==0.2.0
      - setuptools==69.5.1
      - shellingham==1.5.4
      - shtab==1.7.1
      - six==1.17.0
      - sniffio==1.3.1
      - soundfile==0.13.1
      - soupsieve==2.6
      - soxr==0.5.0.post1
      - sse-starlette==2.2.1
      - starlette==0.41.3
      - sympy==1.13.3
      - tabulate==0.9.0
      - termcolor==2.5.0
      - threadpoolctl==3.5.0
      - tiktoken==0.6.0
      - tokenizers==0.21.0
      - tomlkit==0.12.0
      - torch==2.1.0
      - torch-npu==2.1.0.post3
      - tornado==6.4.2
      - tqdm==4.67.1
      - transformers==4.48.2
      - trec-car-tools==2.6
      - trl==0.9.6
      - typer==0.15.1
      - typing-extensions==4.12.2
      - tyro==0.8.14
      - tzdata==2024.2
      - unlzw3==0.2.3
      - urllib3==2.3.0
      - uvicorn==0.34.0
      - uvloop==0.21.0
      - warc3-wet==0.2.5
      - warc3-wet-clueweb09==0.2.5
      - watchfiles==1.0.4
      - websockets==12.0
      - xgrammar==0.1.16
      - xxhash==3.5.0
      - yarl==1.18.3
      - zlib-state==0.1.9
prefix: /home/.conda/envs/deepseek
